#ifndef PUBULICDEFINE_H
#define PUBULICDEFINE_H

#define LOG_FILE_PATH "./busLOG"
#define VERSION_FILE_PATH "./busV"
#define ID_FILE_PATH "./bus.cfg"
#define GET_BUS_IFOR 1
#define GET_SYS_TIME 2
#define GET_ONE_FROM_CQ 3
#define SERVER_IP "http://123.207.75.109:10000/YiYangIndex.ashx?ActionKey="
#define REQUEST_INTERVERL 4500
#define SECOND_FUNCTION_INTERVAL 600
#define WAIT_COM_RETURN_TIME 30
#define DEBUT_WITHOUT_COM 0
#define DEBUG_GET_ONE_STATION_FROM_CQ 1
#define DEBUG_4_DISPLAY 0
#define DEBUG_SHOW_DISTANCE 0
#define DEBUG_RUN_DESKTOP 0
#define NEW_SHOW_1096 1
#define DEBUG_PRINT 0

#endif // PUBULICDEFINE_H
